apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
  JWT_KEY: bXlyYW5kb21wYXNzd29yZA==
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secret
type: Opaque
data:
  STRIPE_KEY: c2tfdGVzdF81MVBMOEpKMDNFem9jQk5PaWdLYjFLcDZPaUhCWU1ENU9RS0tCUms3d2xyQmtQUUZ3UkJYM203dTZRbWNIbzdFc3dWRGJjM2ptUlVFNnc5d3V3YmRGRkt2aDAwMzIyUGg0NVg=

